<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Laboratory Task 5</strong></h4>

**1. Perform Standard Imports**

<br>

**2. Create a function called `set_seed()` that accepts `seed: int` as a parameter, this function must return nothing but just set the seed to a certain value.**

<br>

**3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the `set_seed()` function and use `42` as the seed parameter.**

<br>

**4. Create a tensor "x" from the array above**

<br>

**5. Change the dtype of x from `int32` to `int64`**

<br>

**6. Reshape `x` into a 3x2 tensor** <br> There are several ways to do this.

<br>

**7. Return the right-hand column of tensor `x`**

<br>

**8. Without changing x, return a tensor of square values of `x`** <br> There are several ways to do this.

<br>

**9. Create a tensor `y` with the same number of elements as `x`, that can be matrix-multiplied with `x`** <br> Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed. <br> Think about what shape it should have to permit matrix multiplication.

<br>

**10. Find the matrix product of `x` and `y`.**

</div>

## 1. Imports and Seed Initialization

This section sets up the foundational libraries required for tensor operations and mathematical computations. The set_seed() function is defined to ensure reproducible results across both NumPy and PyTorch environments by fixing the random number generators using torch.manual_seed(). This guarantees that "random" tensor generation will yield the exact same values every time the code runs.

In [1]:
# 1. Perform Standard Imports
import numpy as np
import torch

# 2. Create a function called set_seed()
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

## 2. Array Generation, Tensor Conversion, and Reshaping

Here, a NumPy array of 6 random integers is generated and immediately converted into a PyTorch tensor using torch.from_numpy(). Because PyTorch operations strictly require matching datatypes, the .type() method is explicitly used to cast the tensor from int32 to a 64-bit integer (torch.int64). Finally, the flat tensor is transformed into a 2D matrix (3 rows and 2 columns) using .reshape(), which safely alters the tensor's view without modifying the original memory block.

In [2]:
# 3. Create a NumPy array 
set_seed(42)
arr = np.random.randint(0, 5, 6)

# 4. Create a tensor "x" from the array above
x = torch.from_numpy(arr)

# 5. Change the dtype of x from int32 to int64
x = x.type(torch.int64)

# 6. Reshape x into a 3x2 tensor
x = x.reshape(3, 2)

## 3. Tensor Slicing and Element-wise Operations

This block demonstrates PyTorch's native data manipulation capabilities. Extracting specific values from a tensor uses the exact same slicing syntax as NumPy arrays. The slice [:, 1:] grabs all rows (:) but only the elements from index 1 onwards (1:), effectively returning the right-hand column as a 2D slice. The .pow(2) function performs an element-wise arithmetic power operation, returning a brand new tensor containing the squared values without altering the original tensor x.

In [3]:
# 7. Return the right-hand column of tensor x
right_column = x[:, 1:] 

# 8. Without changing x, return a tensor of square values of x
x_squared = x.pow(2)

## 4. Matrix Creation and Multiplication

To perform a 2D matrix multiplication, the number of columns in the first tensor must perfectly match the number of rows in the second tensor. Since tensor x has the shape (3, 2), the new tensor y is explicitly created from scratch using torch.randint() with an inverted shape of (2, 3). The operation torch.mm(x, y) then calculates the matrix product.

In [4]:
# 9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x
set_seed(42)
y = torch.randint(0, 5, (2, 3))

# 10. Find the matrix product of x and y
matrix_prod = torch.mm(x, y) 

# Print statements to verify the outputs
print("x:\n", x)
print("\nright_column:\n", right_column)
print("\nx_squared:\n", x_squared)
print("\ny:\n", y)
print("\nMatrix Product (x * y):\n", matrix_prod)

x:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])

right_column:
 tensor([[4],
        [4],
        [1]])

x_squared:
 tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

y:
 tensor([[2, 2, 1],
        [4, 1, 0]])

Matrix Product (x * y):
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


**Tensor Reshaping and Slicing Verification**

The printed output of x confirms it was successfully reshaped into a 3x2 configuration. The right_column output [[4], [4], [1]] proves that the slicing operation [:, 1:] successfully extracted the final column while maintaining its proper 2D column-vector shape rather than flattening it into a 1D array.

**Element-Wise Power Dynamics**
The x_squared output directly mirrors the shape of x, proving that basic arithmetic operations like pow() are applied on an element-by-element basis. Every individual scalar inside the matrix was multiplied by itself (e.g., the 3 became 9, the 4 became 16), entirely independently of the other elements in the tensor.   Dimensionality and the Matrix Product
The final output perfectly demonstrates the mathematical laws of matrix multiplication. Tensor x has a size of (3, 2) and tensor y has a size of (2, 3). Because their inner dimensions match (2 columns and 2 rows), the multiplication is valid. The resulting tensor natively adopts the outer dimensions of the two parent matrices, successfully outputting a new tensor with the expected shape of (3, 3).